#GOMOKU CONSTANTS
BOARD_SIZE = 15 #NxN board
#PATHS AND LOGGING
SESSION_MODEL_PATH = "ppo_models/"
EVAL_MODEL_PATH = "best_ppo_models/"
LOG_PATH = "callback_logs/"
TENSORBOARD_LOG_PATH = "tensorboard/"
#NN TRAINING CONSTANTS
N_STEPS =1024
BATCH_SIZE = 512
N_EPOCHS = 2
LEARNING_RATE = 3e-5
CLIP_RANGE = 0.2
GAMMA = 0.99
WEIGHT_DECAY = 1e-6
#BEST MODEL SAVING CONSTANTS (EFFECTS SELF PLAYING PERFORMANCE!)
EVAL_EPISODES = 2
ROLLOUTS_PER_EVAL = 1 # evalate for best model saving every # rollouts
MAX_SAVED_BEST_MODELS = 4 # save the last # history best models, to prevent overfitting
#ARCHITECTURE CONSTANTS
RESIDUAL_BLOCKS = 20
BLOCK_WIDTH = 256
#RENDERING OPTIONS
RENDER_MODE_TRAIN = False
RENDER_MODE_EVAL = False
RENDER_MODE_WAIT_TIME = 0.2