#GOMOKU CONSTANTS
BOARD_SIZE = 15 #NxN board
#PATHS AND LOGGING
SESSION_MODEL_PATH = "ppo_models/"
EVAL_MODEL_PATH = "best_ppo_models/"
LOG_PATH = "callback_logs/"
TENSORBOARD_LOG_PATH = "tensorboard/"
#NN TRAINING CONSTANTS
N_STEPS = 128
LEARNING_RATE = 1e-4
WEIGHT_DECAY = 1e-5
RESIDUAL_BLOCKS = 20
BLOCK_WIDTH = 256
#RENDERING OPTIONS
RENDER_MODE_TRAIN = False
RENDER_MODE_EVAL = False
RENDER_MODE_WAIT_TIME = 0.2